'use strict';
// v2 wave B — Backend harness: build + run jailed mini-apps per bot.
//
// A bot can ask the harness to SCAFFOLD an app inside its own jail
// (data/bots/<bot>/harness/<name>/) and later RUN it with
// `node app.js`. Run discipline (non-negotiable):
//   - spawn('node', [appPath], { cwd }) — NEVER a shell string
//   - cwd + appPath are jail-resolved first (path traversal escapes_jail)
//   - 10 s hard timeout; the child is killed on expiry
//   - stdout/stderr tails capped at 4 KB each
//   - child env is scrubbed: NODE_ENV + loopback-only proxy vars; every
//     other inherited variable (API keys, endpoints) is dropped so a
//     generated app has no network reach beyond localhost by accident.
//
// The executor flow owns auditing (server.js _postAction) — this module is
// pure state + process discipline, like the dispatcher.

const fs = require('node:fs');
const crypto = require('node:crypto');
const path = require('node:path');
const { spawn } = require('node:child_process');

const RUN_TIMEOUT_MS = 10_000;
const TAIL_BYTES = 4 * 1024; // 4 KB stdout/stderr tails
const HARNESS_DIR = 'harness';
const TREES_DIR = 'trees';

// Files every scaffolded app ships with. app.js is plain Node — no deps.
const APP_JS = `'use strict';
// Generated by the Trust Gateway harness for this bot. Zero deps.
// Default mode: print a startup line and exit (so harness.run returns
// quickly). Set HARNESS_SERVE=1 to keep a loopback-only server listening.
const http = require('node:http');

console.log('harness app online');

if (process.env.HARNESS_SERVE === '1') {
  const server = http.createServer((req, res) => {
    res.writeHead(200, { 'content-type': 'application/json' });
    res.end(JSON.stringify({ ok: true, app: 'harness', path: req.url }));
  });
  server.listen(process.env.PORT || 0, '127.0.0.1', () => {
    console.log('harness app listening on 127.0.0.1:' + server.address().port);
  });
}
`;

const INDEX_HTML = `<!doctype html>
<html><head><meta charset="utf-8"><title>harness app</title></head>
<body><h1>harness app</h1><p id="status">scaffolded</p></body></html>
`;

const PACKAGE_JSON = () => JSON.stringify({
  name: 'harness-app',
  version: '0.0.1',
  private: true,
  description: 'Generated by the Trust Gateway harness — zero npm deps.',
}, null, 2) + '\n';

const README_MD = (name) => `# harness app: ${name}

Scaffolded inside this bot's jail by the Trust Gateway backend harness.
Run it with the \`harness.run:${name}\` tool (node app.js, 10 s cap,
loopback-only env). Zero npm dependencies by platform rule.
`;

function tryRealpath(p) {
  try { return fs.realpathSync(p); } catch { return undefined; }
}

function tail(s) {
  if (s.length <= TAIL_BYTES) return s;
  return s.slice(-TAIL_BYTES);
}

/**
 * Jail resolution copied from dispatcher.js (same semantics, minimal shape):
 * rejects absolute paths and '..' segments, then verifies realpath of the
 * destination (or deepest existing ancestor) stays inside realRoot.
 * Throws Error('escapes_jail') on any violation.
 */
function jailResolve(target, rootDir) {
  if (typeof target !== 'string' || target.length === 0) {
    throw Object.assign(new Error('escapes_jail'), { code: 'ESCAPES_JAIL' });
  }
  if (path.isAbsolute(target)) {
    throw Object.assign(new Error('escapes_jail'), { code: 'ESCAPES_JAIL' });
  }
  const parts = target.split(path.sep);
  if (parts.some((p) => p === '..')) {
    throw Object.assign(new Error('escapes_jail'), { code: 'ESCAPES_JAIL' });
  }
  const resolved = path.resolve(rootDir, target);
  const realRoot = tryRealpath(rootDir);
  const realTarget = tryRealpath(resolved);
  if (realTarget !== undefined) {
    if (realTarget !== realRoot && !realTarget.startsWith(realRoot + path.sep)) {
      throw Object.assign(new Error('escapes_jail'), { code: 'ESCAPES_JAIL' });
    }
    return realTarget;
  }
  let p = path.dirname(resolved);
  let realAncestor;
  while (p !== rootDir && p !== path.parse(p).dir) {
    realAncestor = tryRealpath(p);
    if (realAncestor !== undefined) break;
    p = path.dirname(p);
  }
  if (realAncestor === undefined) realAncestor = realRoot;
  const tailRel = path.relative(rootDir, resolved);
  const canonical = path.join(realAncestor, tailRel);
  if (canonical !== realRoot && !canonical.startsWith(realRoot + path.sep)) {
    throw Object.assign(new Error('escapes_jail'), { code: 'ESCAPES_JAIL' });
  }
  return canonical;
}

function ensureDir(dir) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  return tryRealpath(dir) || path.resolve(dir);
}

function copyDir(src, dest) {
  fs.mkdirSync(dest, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const s = path.join(src, entry.name);
    const d = path.join(dest, entry.name);
    if (entry.isDirectory()) copyDir(s, d);
    else if (entry.isFile()) fs.copyFileSync(s, d);
  }
}

function rmDirSafe(dir) {
  fs.rmSync(dir, { recursive: true, force: true });
}

/**
 * @param {{ botsDir: string }} opts
 */
function makeHarness({ botsDir } = {}) {
  if (!botsDir) throw new Error('makeHarness requires { botsDir }');
  const root = path.resolve(botsDir);
  const botRoot = (bot) => path.join(root, String(bot));

  // ── harness.build:<name> ──────────────────────────────────────
  // Scaffolds app.js, index.html, package.json, README.md under
  // data/bots/<bot>/harness/<name>/. Returns jail-relative paths only.
  async function build(bot, name, files) {
    if (typeof bot !== 'string' || !bot.length) {
      throw Object.assign(new Error('escapes_jail'), { code: 'ESCAPES_JAIL' });
    }
    if (typeof name !== 'string' || !/^[A-Za-z0-9._-]+$/.test(name) || name.startsWith('.')) {
      return { ok: false, error: 'bad_name' };
    }
    const rootDir = ensureDir(botRoot(bot));
    const appDirReal = jailResolve(`${HARNESS_DIR}/${name}`, rootDir);
    fs.mkdirSync(appDirReal, { recursive: true });

    const written = [];
    const write = (rel, content) => {
      const p = path.join(appDirReal, rel);
      fs.writeFileSync(p, content, 'utf8');
      written.push(`${HARNESS_DIR}/${name}/${rel}`);
    };

    write('app.js', (files && typeof files.appJs === 'string') ? files.appJs : APP_JS);
    write('index.html', (files && typeof files.indexHtml === 'string') ? files.indexHtml : INDEX_HTML);
    write('package.json', (files && typeof files.packageJson === 'string') ? files.packageJson : PACKAGE_JSON());
    write('README.md', (files && typeof files.readmeMd === 'string') ? files.readmeMd : README_MD(name));

    return { ok: true, name, paths: written, dir: `${HARNESS_DIR}/${name}` };
  }

  // ── harness.run:<name> ────────────────────────────────────────
  // Runs node app.js inside the jail. stdout/stderr tails (4 KB), exit
  // code, duration. Env scrubbed to loopback-only. Hard 10 s timeout.
  async function run(bot, name) {
    if (typeof bot !== 'string' || !bot.length) {
      throw Object.assign(new Error('escapes_jail'), { code: 'ESCAPES_JAIL' });
    }
    if (typeof name !== 'string' || !/^[A-Za-z0-9._-]+$/.test(name) || name.startsWith('.')) {
      return { ok: false, error: 'bad_name' };
    }
    const rootDir = ensureDir(botRoot(bot));
    const dir = jailResolve(`${HARNESS_DIR}/${name}`, rootDir);
    const appPath = jailResolve(`${HARNESS_DIR}/${name}/app.js`, rootDir);
    if (!fs.existsSync(appPath)) return { ok: false, error: 'app_not_found', name };

    const env = {
      PATH: process.env.PATH || '/usr/bin:/bin',
      HOME: process.env.HOME || '/tmp',
      NODE_ENV: 'production',
      // loopback-only: no outbound proxies, no outbound endpoints
      HTTP_PROXY: '127.0.0.1:9',
      HTTPS_PROXY: '127.0.0.1:9',
      NO_PROXY: '127.0.0.1,localhost',
    };

    return new Promise((resolve) => {
      const started = Date.now();
      const child = spawn('node', [appPath], {
        cwd: dir,
        env,
        stdio: ['ignore', 'pipe', 'pipe'],
      });
      let out = '';
      let err = '';
      let done = false;
      const timer = setTimeout(() => {
        if (done) return;
        done = true;
        try { child.kill('SIGKILL'); } catch { /* already gone */ }
        resolve({
          ok: true, name, exitCode: null, timedOut: true,
          stdout: tail(out), stderr: tail(err),
          durationMs: Date.now() - started,
        });
      }, RUN_TIMEOUT_MS);

      child.stdout.on('data', (c) => { out += c.toString('utf8'); });
      child.stderr.on('data', (c) => { err += c.toString('utf8'); });
      child.on('error', (e) => {
        if (done) return;
        done = true;
        clearTimeout(timer);
        resolve({ ok: true, name, exitCode: 1, timedOut: false, stdout: tail(out), stderr: tail(`${err}${err ? '\n' : ''}${e.message}`), durationMs: Date.now() - started });
      });
      child.on('close', (code) => {
        if (done) return;
        done = true;
        clearTimeout(timer);
        resolve({
          ok: true, name, exitCode: code, timedOut: false,
          stdout: tail(out), stderr: tail(err),
          durationMs: Date.now() - started,
        });
      });
    });
  }

  // ── worktree.snapshot:<name> (tree snapshots — no git in jail) ──
  // Copies data/bots/<bot>/harness/<name>/ → data/bots/<bot>/trees/<name>-<ts>/
  async function snapshot(bot, name) {
    if (typeof bot !== 'string' || !bot.length) {
      throw Object.assign(new Error('escapes_jail'), { code: 'ESCAPES_JAIL' });
    }
    if (typeof name !== 'string' || !/^[A-Za-z0-9._-]+$/.test(name) || name.startsWith('.')) {
      return { ok: false, error: 'bad_name' };
    }
    const rootDir = ensureDir(botRoot(bot));
    const src = jailResolve(`${HARNESS_DIR}/${name}`, rootDir);
    if (!fs.existsSync(src)) return { ok: false, error: 'not_found', name };
    // ms-precision timestamp alone collides when two snapshots land in the same
    // millisecond (seen under parallel shard load); add a random suffix.
    const ts = new Date().toISOString().replace(/[:.]/g, '-') + '-' + crypto.randomBytes(3).toString('hex');
    const id = `${name}-${ts}`;
    const dest = jailResolve(`${TREES_DIR}/${id}`, rootDir);
    copyDir(src, dest);
    return { ok: true, id, name, path: `${TREES_DIR}/${id}`, files: countFiles(dest) };
  }

  // ── worktree.remove:<id> ─────────────────────────────────────
  // Deletes data/bots/<bot>/trees/<id>. Jail-guarded.
  async function remove(bot, id) {
    if (typeof bot !== 'string' || !bot.length) {
      throw Object.assign(new Error('escapes_jail'), { code: 'ESCAPES_JAIL' });
    }
    if (typeof id !== 'string' || !/^[A-Za-z0-9._-]+$/.test(id) || id.startsWith('.')) {
      return { ok: false, error: 'bad_id' };
    }
    const rootDir = ensureDir(botRoot(bot));
    const target = jailResolve(`${TREES_DIR}/${id}`, rootDir);
    if (!fs.existsSync(target)) return { ok: false, error: 'not_found', id };
    rmDirSafe(target);
    return { ok: true, id, removed: `${TREES_DIR}/${id}` };
  }

  // ── worktree.list / GET /v2/trees support ─────────────────────
  function listTrees(bot) {
    if (typeof bot !== 'string' || !bot.length) {
      throw Object.assign(new Error('escapes_jail'), { code: 'ESCAPES_JAIL' });
    }
    const rootDir = ensureDir(botRoot(bot));
    const treesRoot = path.join(rootDir, TREES_DIR);
    if (!fs.existsSync(treesRoot)) return [];
    const out = [];
    for (const entry of fs.readdirSync(treesRoot, { withFileTypes: true }).sort()) {
      if (!entry.isDirectory()) continue;
      const stat = fs.statSync(path.join(treesRoot, entry.name));
      out.push({
        id: entry.name,
        path: `${TREES_DIR}/${entry.name}`,
        files: countFiles(path.join(treesRoot, entry.name)),
        createdAt: stat.mtime.toISOString(),
      });
    }
    return out;
  }

  function countFiles(dir) {
    let n = 0;
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (entry.isDirectory()) n += countFiles(path.join(dir, entry.name));
      else if (entry.isFile()) n += 1;
    }
    return n;
  }

  return { build, run, snapshot, remove, listTrees, jailResolve };
}

module.exports = { makeHarness, jailResolve, HARNESS_DIR, TREES_DIR, RUN_TIMEOUT_MS, TAIL_BYTES };